"""create_doctors_services_doctor_working_hours

Revision ID: 02dc00970591
Revises: 2fef91c74a30
Create Date: 2026-09-29 23:05:54.690445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02dc00970591'
down_revision: Union[str, None] = '2fef91c74a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doctors_clinic_id', 'doctors', ['clinic_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_services_clinic_id', 'services', ['clinic_id'], unique=False)
    op.create_table('doctor_working_hours',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doctor_working_hours_clinic_id', 'doctor_working_hours', ['clinic_id'], unique=False)
    op.create_index('ix_doctor_working_hours_doctor_day', 'doctor_working_hours', ['doctor_id', 'day_of_week'], unique=False)
    op.create_index('ix_doctor_working_hours_doctor_id', 'doctor_working_hours', ['doctor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doctor_working_hours_doctor_id', table_name='doctor_working_hours')
    op.drop_index('ix_doctor_working_hours_doctor_day', table_name='doctor_working_hours')
    op.drop_index('ix_doctor_working_hours_clinic_id', table_name='doctor_working_hours')
    op.drop_table('doctor_working_hours')
    op.drop_index('ix_services_clinic_id', table_name='services')
    op.drop_table('services')
    op.drop_index('ix_doctors_clinic_id', table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
